language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t marjugoncalves/react-end-to-end-pipeline -f Dockerfile.dev .

script:
  - docker run -e CI=true marjugoncalves/react-end-to-end-pipeline npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-389082447763"
  bucket_path: "react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"